[WIP] add tests for controller_manager scripts
ros-controls/ros_control pull request #288
Opened 2017-10-30 23:26 UTC by ipa-mdl

addresses #287 

I have added some basic tests without argument tests.
To make the tests work I had to fix a bug in controller_manager list.

In addtion I have refactored the `unspawner` script.
This alters the behavior a little bit, but prevents any infinite blocking.

2017-11-01 12:53 UTC, ipa-mdl commented
The test fail because the spawner hits a rospy bug which does not handle certain error cases correctly.
#284 should fix it on our side.

2017-11-06 10:52 UTC, bmagyar commented
Is this still a WIP? My merging finger is itchy! :)

2017-11-06 10:52 UTC, bmagyar approved these changes

2017-11-07 16:49 UTC, mathias-luedtke commented
I am not sure about the `unspawner`, I don't know if this is used by someone at all..

2017-11-07 16:52 UTC, bmagyar commented
I used it on some PAL robots, it's  probably still that way.

On Nov 7, 2017 16:49, "Mathias Lüdtke" <notifications@github.com> wrote:

> I am not sure about the unspawner, I don't if this is used by someone at
> all..
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros-controls/ros_control/pull/288#issuecomment-342545980>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADXH4ewg65wf895MPwklq7FiW-mBHb1gks5s0IoKgaJpZM4QL_se>
> .
>

2017-11-23 14:30 UTC, bmagyar requested changes

2017-11-23 14:30 UTC, bmagyar commented on controller_manager_tests/test/controller_manager_scripts.py
> +        run_cm('load', 'my_controller2') # TODO: check output
Aren't these TODO-s supposed to be done too? ;)

2017-11-28 13:34 UTC, bmagyar commented on controller_manager_tests/test/controller_manager_scripts.py
> +        run_cm('load', 'my_controller2') # TODO: check output
@ipa-mdl Any notes on this?

2017-12-23 12:24 UTC, bmagyar commented
Ping @ipa-mdl

2017-12-24 11:51 UTC, ipa-mdl commented
I might fix the TODOs after the holidays..

2018-01-04 15:41 UTC, mikepurvis commented
LGTM

2018-01-09 10:43 UTC, ipa-mdl commented
updated to check all ouput
@bmagyar: please review again

2018-01-09 13:30 UTC, bmagyar approved these changes

2018-01-09 13:32 UTC, merged