Update transmission parser to parse the joint role
ros-controls/ros_control pull request #318
Opened 2018-04-11 17:52 UTC by jlack1987

This is to fix #317

2018-04-11 18:23 UTC, jlack1987 commented
No clue how my commits caused a CI failure. The following looks like the error output that's causing the problem,
```
Full test results for 'build/transmission_interface/test_results/transmission_interface/MISSING-gtest-differential_transmission_loader_test.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="gtest-differential_transmission_loader_test.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
    <failure message="Unable to find test results for gtest-differential_transmission_loader_test.xml, test did not run.
Expected results in /root/catkin_ws/build/transmission_interface/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml" type=""/>
  </testcase>
</testsuite>
-------------------------------------------------
Full test results for 'build/transmission_interface/test_results/transmission_interface/MISSING-gtest-four_bar_linkage_transmission_loader_test.xml'
-------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="1" failures="1" time="1" errors="0" name="gtest-four_bar_linkage_transmission_loader_test.xml">
  <testcase name="test_ran" status="run" time="1" classname="Results">
    <failure message="Unable to find test results for gtest-four_bar_linkage_transmission_loader_test.xml, test did not run.
Expected results in /root/catkin_ws/build/transmission_interface/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml" type=""/>
  </testcase>
</testsuite>
-------------------------------------------------
build/transmission_interface/test_results/transmission_interface/MISSING-gtest-differential_transmission_loader_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
build/transmission_interface/test_results/transmission_interface/MISSING-gtest-four_bar_linkage_transmission_loader_test.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```
not sure how my commit had an affect on that

2018-04-16 11:42 UTC, bmagyar commented
I've ran the tests in a local docker container. Note below the **Segmentation fault (core dumped)** appearing on both tests that report failure here.

```
-- run_tests.py: execute commands
  /root/ws/devel/lib/transmission_interface/four_bar_linkage_transmission_loader_test --gtest_output=xml:/root/ws/build/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from FourBarLinkageTransmissionLoaderTest
[ RUN      ] FourBarLinkageTransmissionLoaderTest.FullSpec
[       OK ] FourBarLinkageTransmissionLoaderTest.FullSpec (20 ms)
[ RUN      ] FourBarLinkageTransmissionLoaderTest.MinimalSpec
[       OK ] FourBarLinkageTransmissionLoaderTest.MinimalSpec (1 ms)
[ RUN      ] FourBarLinkageTransmissionLoaderTest.InvalidSpec
Segmentation fault (core dumped)
-- run_tests.py: verify result "/root/ws/build/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml"
Cannot find results, writing failure results to '/root/ws/build/test_results/transmission_interface/MISSING-gtest-four_bar_linkage_transmission_loader_test.xml'
[ 56%] Built target run_tests_transmission_interface_gtest_four_bar_linkage_transmission_loader_test
[ 68%] Built target differential_transmission_loader_test
Scanning dependencies of target run_tests_transmission_interface_gtest_differential_transmission_loader_test
-- run_tests.py: execute commands
  /root/ws/devel/lib/transmission_interface/differential_transmission_loader_test --gtest_output=xml:/root/ws/build/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from DifferentialTransmissionLoaderTest
[ RUN      ] DifferentialTransmissionLoaderTest.FullSpec
[       OK ] DifferentialTransmissionLoaderTest.FullSpec (26 ms)
[ RUN      ] DifferentialTransmissionLoaderTest.MinimalSpec
[       OK ] DifferentialTransmissionLoaderTest.MinimalSpec (1 ms)
[ RUN      ] DifferentialTransmissionLoaderTest.InvalidSpec
Segmentation fault (core dumped)
-- run_tests.py: verify result "/root/ws/build/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml"
```

2018-04-16 15:20 UTC, jlack1987 commented
It looks like the problem is the `GetText()` function call returns a `nullptr` if the field is an empty string which is what's happening. I fixed it, but noticed there's lots of other places in the transmission parser code where this could result in a segfault. Found [this thread](https://github.com/leethomason/tinyxml2/issues/105) where it talks about it a bit.

2018-04-16 15:32 UTC, bmagyar commented
I see. Not sure if this is better, it's definitely more brief:
```
joint.role_ =  role_it->GetText() ? role_it->GetText() : std::string()
```

2018-04-16 15:47 UTC, jlack1987 commented
Agreed it is more concise, thanks for the suggestion. Have made the update.

2018-04-16 16:08 UTC, bmagyar requested changes
Could you please add a test that ensures that an empty role tag gets us an empty string?

2018-04-16 16:08 UTC, bmagyar commented on transmission_interface/src/transmission_parser.cpp
> +      joint.role_ =  role_it->GetText() ? role_it->GetText() : std::string();
There's an extra space after "="

2018-04-16 17:29 UTC, jlack1987 commented on transmission_interface/src/transmission_parser.cpp
> +      joint.role_ =  role_it->GetText() ? role_it->GetText() : std::string();
Fixed

2018-04-17 07:42 UTC, bmagyar approved these changes

2018-04-17 07:43 UTC, bmagyar commented
Thanks!

2018-04-17 07:43 UTC, merged