Added quotes for controller name and controller type in warnings and errors
ros-controls/ros_control pull request #342
Opened 2018-07-04 11:23 UTC by jgueldenstein

This PR provides some consistency in the warnings and errors printed by the controller manager.
Having quotes around the controller requested to be spawned is especially useful when the controller name was left empty or contains whitespace.

It would also be nice to have this in kinetic too

@v4hn

2018-07-04 15:55 UTC, bmagyar commented
LGTM :+1: 

@ipa-mdl please review and merge if ok for you too.

2018-07-04 15:55 UTC, bmagyar approved these changes

2018-07-04 15:58 UTC, bmagyar requested changes
Actually... I think the same should be applied to the Python interfaces as well.

2018-07-06 18:57 UTC, ipa-mdl commented
The migration to `rosconsole` breaks the corresponding [test](https://github.com/ros-controls/ros_control/blob/melodic-devel/controller_manager_tests/test/controller_manager_scripts.py).
Does this even work properly? The script does not start a node ..

2018-07-08 08:41 UTC, v4hn commented
Why does changing to `rospy.loginfo` result in
`controller_manager_tests/EffortTestController' missing?
Or do I misunderstand the CI output?

The code around the `print`'s in question calls ROS services.
That might even be possible without being a node, but
I would still expect that users only use this within a ROS node.

What do you propose to resolve this?

2018-07-08 08:47 UTC, bmagyar commented
Could we undo the rosconsole migration in the python parts please? 
This library supports command line tools and as such it creates it's output directly on stdout. 

@v4hn the tests are failing because we specifically test for the right text output.

2018-07-08 09:09 UTC, v4hn commented
Makes sense.

2018-07-08 11:56 UTC, ipa-mdl commented
> Could we undo the rosconsole migration in the python parts please?

As an alternative the tests could be adapted to strip the rosconsole prefix (with the varying time stamp..).

2018-07-11 08:56 UTC, jgueldenstein commented
I will undo the rosconsole part and adapt the tests as soon as I get to it.

2018-07-19 12:42 UTC, jgueldenstein commented
I had some time to look at the test results. I do not know why the occuring error
``
[controller_manager_tests.rosunit-controller_manager_interface_test/test_scripts][passed]
[controller_manager_tests.rosunit-controller_manager_scripts_test/test_scripts][FAILURE]
'controller_manager_tests/EffortTestController' not found in []
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/root/catkin_ws/src/ros_control/controller_manager_tests/test/controller_manager_scripts.py", line 56, in test_scripts
    self.assertIn('controller_manager_tests/EffortTestController', listed_types)
  File "/usr/lib/python2.7/unittest/case.py", line 804, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
--------------------------------------------------------------------------------
``
starting in line 4169 could be related to these changes in the code.
Please have a look.

2018-08-03 12:09 UTC, jgueldenstein commented
ping

2018-08-05 21:34 UTC, bmagyar commented
You haven't undone the rosconsole parts, this means that the tests that are capturing `stdout` will get empty strings from the subprocess calls. 

I've also spotted a few other places where I had to add `'`-s and adjusted the expected strings in the test.

2018-08-06 14:13 UTC, v4hn commented
Thanks @bmagyar !
Tests pass now.

2018-08-06 15:47 UTC, bmagyar approved these changes

2018-08-06 15:48 UTC, bmagyar commented
@ipa-mdl could you please give a wee look and merge if all ok?

2018-08-07 07:52 UTC, jgueldenstein commented
Ok thank you for clarifying, I was just confused that a test which seemed totally unrelated failed.
Also thank you for fixing.

2018-08-16 06:29 UTC, bmagyar commented
Extending to: @ipa-mdl or @graiola

2018-08-16 12:45 UTC, merged