use this_thread::sleep_for on Windows
ros-controls/ros_control pull request #375
Opened 2019-02-01 01:07 UTC by kejxu

very similar to https://github.com/ros-controls/realtime_tools/pull/32, `usleep` is not available on Windows. use `this_thread::sleep_for` from `c++11` instead

additionally, some refactoring changes are also introduced to improve readability

2019-02-01 08:57 UTC, mathias-luedtke requested changes
Same response :D
Please use `std::chrono`everywhere.

2019-02-03 09:04 UTC, bmagyar approved these changes
Lovely! 

Thumbs up for touching up those braces, looks much better

2019-02-03 09:05 UTC, bmagyar commented
@ipa-mdl please make sure to squash-merge

2019-02-04 17:15 UTC, mathias-luedtke approved these changes

2019-02-04 17:16 UTC, merged