[trivial but useful] Allow spawner to wait indefinitely if requested
ros-controls/ros_control pull request #428
Opened 2020-03-12 13:21 UTC by v4hn

`rospy.wait_for_service` does not allow for `0` to wait indefinitely.
Instead `None` has to be passed explicitly.

A user-provided value of 0 leads to an error message and failure at the moment, so it is alright to use the value to indicate indefinite waiting time.

2020-03-12 16:06 UTC, matthew-reynolds requested changes
Seems reasonable, but since this will make the `timeout` behaviour slightly different than `rospy.wait_for_service`, we should add more info. For example, in the help string for the `timeout` argparse argument, maybe add something along the lines of "If <=0, wait indefinitely".

Alternatively/in addition, we could add a `--no-timeout` argument. Might be clearer to users. Thoughts?

2020-03-12 17:02 UTC, destogl commented
+1 for --no-timeout

2020-03-12 17:21 UTC, bmagyar commented
I see value in both using the number to encode wait time (if passed in through a parameter) and the more verbose option. Can we have both please? ;)

2020-03-13 06:19 UTC, v4hn commented
Wow, it *is* a trivial patch obviously improving applicability in a case that was not documented *at all* before.
I barely care whether it gets merged or not, I just took a minute to pull-request what I typed locally.

So I'm a bit surprised to get further request for icing and sprinkles. *sigh*
Anyway addressed.

2020-03-13 13:31 UTC, matthew-reynolds approved these changes
Looks great, thanks so much for iterating.

> It is a trivial patch obviously improving applicability in a case that was not documented at all before

Indeed, thanks for pointing out the flaw. Once it was identified, I figured we might as well handle it fully. Always good to strive for the best code we can :)

2020-03-14 11:11 UTC, bmagyar commented
@v4hn indeed sometimes it is unusual to be on the receiving end of reviews ;)

2020-03-14 11:12 UTC, bmagyar approved these changes
Thanks very much for pointing this out and providing a fix!

2020-03-14 11:12 UTC, merged