Fixed compile tests
ros-controls/ros_control pull request #434
Opened 2020-04-01 10:52 UTC by ahcorde

Tests are not able to find `resource_retriever/retriever.h` headers

Signed-off-by: ahcorde <ahcorde@gmail.com>

2020-04-02 06:12 UTC, matthew-reynolds requested changes

2020-04-02 06:12 UTC, matthew-reynolds commented on transmission_interface/CMakeLists.txt
> +  include_directories(include ${resource_retriever_INCLUDE_DIRS})
Thanks! I definitely missed that in my cleanup of these files... 😬.

We can drop this extra `include`, correct?

```suggestion
  include_directories(${resource_retriever_INCLUDE_DIRS})
```

2020-04-02 06:49 UTC, ahcorde commented
thank your for the review @matthew-reynolds

2020-04-03 08:34 UTC, bmagyar commented
How did this issue not show up on our CI?

2020-04-05 03:12 UTC, matthew-reynolds commented
> How did this issue not show up on our CI?

Probably because `${catkin_INCLUDE_DIRS}` always contains `/opt/ros/melodic/include`.

<sup>(Maybe you could come up with some minimal, contrived, barely-even-ROS example that doesn't include that dir, but in all practical cases, it's always included.)</sup>

2020-04-05 11:01 UTC, merged